export const variables = ({
  jobAccepted: false,
  netsMoved: false,
  raffaeleTruthUnlocked: false,
  letterDelivered: false,
  pulleyTroubleKnown: false,
  wellLubricated: false,
  wellFreed: false,
  winchRepaired: false,
  boatReady: false,
  raffaeleConfrontationReady: false,
  driftingBoatSeen: false,
  boatLanded: false,
  sailorEncountered: false,
  bundleOpened: false,
  sealRead: false,
  registryRead: false,
  sailorDied: false,
} satisfies Readonly<Record<string, boolean>>);
