import { Assets, Rectangle, Texture } from "pixi.js";

/**
 * A row of equal-sized animation frames in one image.
 *
 * Generated by tools/build_sprite.py, which guarantees the two properties the
 * engine relies on: every cell is the same size, and the character's feet sit
 * on the bottom edge of their cell. Without the second, swapping poses would
 * make them hop.
 */
export interface SpriteStrip {
  url: string;
  frames: number;
  width: number;
  height: number;
}

/** Cuts a strip into its frames, ready to hand to an AnimatedSprite. */
export async function loadFrames(strip: SpriteStrip): Promise<Texture[]> {
  const sheet = await Assets.load<Texture>(strip.url);
  sheet.source.scaleMode = "nearest";

  return Array.from({ length: strip.frames }, (_, i) => {
    return new Texture({
      source: sheet.source,
      frame: new Rectangle(i * strip.width, 0, strip.width, strip.height),
    });
  });
}
