#!/usr/bin/env python3
"""Turn a concept walk-cycle sheet into a game-ready sprite strip.

The concept sheets come at whatever size the generator produced, on whatever
ground colour, with the figures at inconsistent positions in their cells. The
engine wants the opposite: every frame the same size, on a transparent ground,
with the character's feet at a known point so a pose swap never makes them
hop.

Frames are keyed off the sheet's own corner pixel, so dark, light and
transparent grounds all work without being told which.

Usage:
    tools/build_sprite.py art/concept/personaggi/michele-walk-cycle-v4.png michele-walk
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ART_DIR = Path("art/sprites")
CODE_DIR = Path("src/sprites")

# The character's height at full scale, i.e. standing at the very front of a
# room. Everything further back is scaled down from this, never up: enlarging
# pixel art past its drawn size is the one operation that always looks cheap.
NATIVE_HEIGHT = 100
COLOURS = 32


def runs(flags, minimum: int) -> list[tuple[int, int]]:
    spans, start = [], None
    for i, present in enumerate(flags):
        if present and start is None:
            start = i
        elif not present and start is not None:
            if i - start > minimum:
                spans.append((start, i))
            start = None
    if start is not None and len(flags) - start > minimum:
        spans.append((start, len(flags)))
    return spans


def extract(sheet: Path) -> list[Image.Image]:
    im = Image.open(sheet).convert("RGB")
    pixels = np.asarray(im, dtype=np.int32)
    ground = np.asarray(im.getpixel((2, 2)), dtype=np.int32)
    content = np.abs(pixels - ground).sum(axis=2) > 60

    frames = []
    for y0, y1 in runs(content.sum(axis=1) > 3, minimum=60):
        for x0, x1 in runs(content[y0:y1].sum(axis=0) > 0, minimum=20):
            block = content[y0:y1, x0:x1]
            ys, xs = np.where(block)
            cut = im.crop((x0 + xs.min(), y0 + ys.min(), x0 + xs.max() + 1, y0 + ys.max() + 1))
            alpha = np.where(
                np.abs(np.asarray(cut, dtype=np.int32) - ground).sum(axis=2) > 70, 255, 0
            ).astype(np.uint8)
            frames.append(Image.fromarray(np.dstack([np.asarray(cut, dtype=np.uint8), alpha]), "RGBA"))
    return frames


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sheet", type=Path)
    parser.add_argument("name")
    parser.add_argument("--height", type=int, default=NATIVE_HEIGHT)
    parser.add_argument("--colours", type=int, default=COLOURS)
    args = parser.parse_args()

    frames = extract(args.sheet)
    if not frames:
        print(f"nessun frame trovato in {args.sheet}", file=sys.stderr)
        return 1

    # One scale factor for the whole set, taken from the tallest frame, so a
    # pose with a wider stride does not come out a different height from the
    # rest — which would read as the character bobbing.
    tallest = max(f.height for f in frames)
    factor = args.height / tallest
    scaled = [
        f.resize((max(1, round(f.width * factor)), max(1, round(f.height * factor))), Image.LANCZOS)
        for f in frames
    ]

    cell_w = max(f.width for f in scaled)
    cell_h = max(f.height for f in scaled)

    strip = Image.new("RGBA", (cell_w * len(scaled), cell_h), (0, 0, 0, 0))
    for i, frame in enumerate(scaled):
        # Centred horizontally and sat on the floor of the cell: the anchor is
        # the midpoint of the bottom edge, which is where the feet are.
        strip.paste(frame, (i * cell_w + (cell_w - frame.width) // 2, cell_h - frame.height), frame)

    # Quantise the colour, not the alpha: a palette pass over RGBA turns soft
    # edges into a fringe, so the alpha is lifted out and put back afterwards.
    alpha = strip.getchannel("A")
    body = strip.convert("RGB").quantize(colors=args.colours, method=Image.MEDIANCUT).convert("RGB")
    body.putalpha(alpha)

    ART_DIR.mkdir(parents=True, exist_ok=True)
    png = ART_DIR / f"{args.name}.png"
    body.save(png)

    CODE_DIR.mkdir(parents=True, exist_ok=True)
    module = CODE_DIR / f"{args.name}.ts"
    module.write_text(
        f'import url from "../../art/sprites/{args.name}.png";\n\n'
        'import type { SpriteStrip } from "../engine/sprite";\n\n'
        f"/** Generated by tools/build_sprite.py from {args.sheet.name}. Do not hand-edit. */\n"
        f"export const {to_camel(args.name)}: SpriteStrip = {{\n"
        f"  url,\n"
        f"  frames: {len(scaled)},\n"
        f"  width: {cell_w},\n"
        f"  height: {cell_h},\n"
        "};\n"
    )

    print(f"{png}  ({len(scaled)} frame da {cell_w}x{cell_h}, {args.colours} colori)")
    print(f"{module}")
    return 0


def to_camel(name: str) -> str:
    head, *rest = name.split("-")
    return head + "".join(part.capitalize() for part in rest)


if __name__ == "__main__":
    raise SystemExit(main())
