export {
  AuthoringError,
  type AuthoringDiagnostic,
  type AuthoringDiagnosticFamily,
  type AuthoringDiagnosticOwner,
} from "./capabilities/game-project/diagnostics";
export {
  commandVerbs,
  defineCommandLexicon,
  defineNoun,
  type CommandCase,
  type CommandFallback,
  type CommandLexicon,
  type CommandResponse,
  type CommandVerb,
  type NounDefinition,
  type NounLabel,
  type PreferredVerbCase,
  type SelectedObjectVerbCase,
  type Verb,
} from "./capabilities/interaction";
export {
  defineHUDTheme,
  type HUDTheme,
  type PassageDirection,
} from "./capabilities/hud";
export {
  defineGame,
  defineCharacter,
  defineScene,
  defineObject,
  defineSequence,
  type CharacterDefinition,
  type AnimationDefinition,
  type AnimationFrames,
  type AnimationRoles,
  type AnimationStrip,
  type Appearance,
  type ArrivalSequenceRule,
  type AnimationDirection,
  type CameraDirection,
  type CueStart,
  type DirectionStep,
  type DirectedSubject,
  type Facing,
  type GameProject,
  type LogicalResolution,
  type MotionDirection,
  type GameOperation,
  type HotspotDefinition,
  type InteractionCondition,
  type Line,
  type NarrationStep,
  type ObjectDefinition,
  type Point,
  type SceneDefinition,
  type SceneSize,
  type SequenceDefinition,
  type SequenceDirection,
} from "./capabilities/game-project";
export {
  startGame,
  type GameSession,
  type StartGameOptions,
} from "./browser/start-game";
export {
  validateSaveSnapshot,
  type SaveSnapshot,
  type SaveSnapshotValidation,
  type ValidatedSaveSnapshot,
} from "./capabilities/save";
