import url from "../../art/sprites/michele-walk-back.png";

import type { SpriteStrip } from "../engine/sprite";

/** Generated by tools/build_sprite.py from michele-walk-cycle-back.png. Do not hand-edit. */
export const micheleWalkBack: SpriteStrip = {
  url,
  frames: 8,
  width: 39,
  height: 100,
};
