import url from "../../art/sprites/michele-walk-front.png";

import type { SpriteStrip } from "../engine/sprite";

/** Generated by tools/build_sprite.py from michele-walk-cycle-front.png. Do not hand-edit. */
export const micheleWalkFront: SpriteStrip = {
  url,
  frames: 8,
  width: 41,
  height: 100,
};
