import url from "../../art/sprites/michele-walk.png";

import type { SpriteStrip } from "../engine/sprite";

/** Generated by tools/build_sprite.py from michele-walk-cycle-v4.png. Do not hand-edit. */
export const micheleWalk: SpriteStrip = {
  url,
  frames: 8,
  width: 59,
  height: 100,
};
